classDiagram
  class DocString2MDOptions {
    output
    private_def
    toc
    todo
    toml
    uml
  }
  class EventMSG {
    debug
    error
    info
    warning
  }
  class MyFile {
    exists
    path
    status
    absolute() str
    read() str
    resolve() str
    set_path(path: Optional[str]) MyFile
    write(data: str) ExitStatus
  }
  class NodeVisitor {
    generic_visit(node)
    visit(node)
    visit_Constant(node)
  }
  class ExitStatus {
    name
  }
  class PytMod {
    module
    node_lst
    pkg_main_docstring
    ismodule() bool
    read() None
  }
  class Enum {
    name()
    value()
  }
  class Const {
    name
  }
  class EventMSG {
    debug : str
    error : str
    info : str
    warning : str
  }
  class ExitStatus {
    name
  }
  class LogMessages {
    args
    dump
    elapse_time
    file_not_found
    io_err
    logfile
    new_class
    new_func
    new_module
    node_link_analysis_beg
    node_link_analysis_end
    python
    pytmod
    pytmod_extract
    pytmod_mod
    pytmod_script
    result
    unknown_type_of_node
    write_doc
  }
  class LoggingSetup {
    default_format : str
    default_level : str
    encoding : str
    file_format : str
    logfile : str
    simple_format : str
    set_logfile(path: str) 'LoggingSetup'
  }
  class Tag {
    name
  }
  class ModuleDef {
    docstring : str
    get_docstring() str
    get_summary() str
  }
  class NodeDef {
    definition : str
    docstring : str
    level : int
    title : str
    get_definition() str
    get_docstring() str
    get_summary() str
    get_title() str
    get_toc_elem() str
  }
  class NodeLink {
    level : int
    parent : Optional[ASTVisitedNode]
  }
  class ObjVisitor {
    node_lst
    parse(source: str) ast.AST
    visit_ClassDef(node: ast.ClassDef) None
    visit_FunctionDef(node: ast.FunctionDef) None
    visit_Module(node: ast.Module) None
  }
  class ConvMD {
    add_tag(begin_tag: str, end_tag: str) Callable[[F], F]
    colorize_examples() Callable[[F], F]
    dedent() Callable[[F], F]
    html_escape() Callable[[F], F]
    repl_beg_end(begin_regexp: str, end_regexp: str, begin_tag: str, end_tag: str) Callable[[F], F]
    repl_str(old_string: str, new_string: str) Callable[[F], F]
  }
  class DocString2MD {
    get_doc() str
    import_module() ExitStatus
    writedoc() ExitStatus
  }
  class DocString2MDOptions {
    output
    private_def : bool
    toc : bool
    todo
    toml
    uml
  }
  class MyFile {
    exists : bool
    path : Optional[Path]
    status
    absolute() str
    read() str
    resolve() str
    set_path(path: Optional[str]) MyFile
    write(data: str) ExitStatus
  }
  class PytMod {
    module
    node_lst
    pkg_main_docstring
    ismodule() bool
    read() None
  }
  class NamedTuple {
  }
  ExitStatus --|> Enum
  Const --|> Enum
  EventMSG --|> NamedTuple
  ExitStatus --|> Enum
  LogMessages --|> NamedTuple
  LoggingSetup --|> NamedTuple
  Tag --|> Enum
  ModuleDef --|> NamedTuple
  NodeDef --|> NamedTuple
  NodeLink --|> NamedTuple
  ObjVisitor --|> NodeVisitor
  DocString2MDOptions --|> NamedTuple
  MyFile --|> NamedTuple
  DocString2MDOptions --* DocString2MD : __options
  DocString2MDOptions --* DocString2MD : __options
  EventMSG --* LogMessages : logfile
  EventMSG --* LogMessages : args
  EventMSG --* LogMessages : python
  EventMSG --* LogMessages : dump
  EventMSG --* LogMessages : result
  EventMSG --* LogMessages : elapse_time
  EventMSG --* LogMessages : pytmod
  EventMSG --* LogMessages : pytmod_mod
  EventMSG --* LogMessages : pytmod_script
  EventMSG --* LogMessages : pytmod_extract
  EventMSG --* LogMessages : new_module
  EventMSG --* LogMessages : new_class
  EventMSG --* LogMessages : new_func
  EventMSG --* LogMessages : node_link_analysis_beg
  EventMSG --* LogMessages : node_link_analysis_end
  EventMSG --* LogMessages : unknown_type_of_node
  EventMSG --* LogMessages : io_err
  EventMSG --* LogMessages : file_not_found
  EventMSG --* LogMessages : write_doc
  MyFile --* DocString2MDOptions : toml
  MyFile --* DocString2MDOptions : uml
  MyFile --* DocString2MDOptions : todo
  MyFile --* DocString2MDOptions : output
  ExitStatus --* MyFile : status
  PytMod --* DocString2MD : __my_module
  PytMod --* DocString2MD : __my_module
