classDiagram
  class docstring2md {
  }
  class __about__ {
  }
  class __config__ {
  }
  class ast_engine {
  }
  class cli {
  }
  class convmd {
  }
  class doc2md {
  }
  class file {
  }
  class log {
  }
  class mod {
  }
  docstring2md --> __about__
  docstring2md --> doc2md
  docstring2md --> file
  docstring2md --> log
