from docstring2md.__config__ import ExitStatus as ExitStatus, LOGGING_SETUP as LOGGING_SETUP, LOG_MSG as LOG_MSG
from docstring2md.log import logger as logger
from pathlib import Path
from typing import NamedTuple, Optional

class MyFile(NamedTuple):
    path: Optional[Path]
    exists: bool
    status: ExitStatus
    @classmethod
    def set_path(cls, path: Optional[str]) -> MyFile: ...
    def read(self) -> str: ...
    def write(self, data: str) -> ExitStatus: ...
    def resolve(self) -> str: ...
    def absolute(self) -> str: ...
