from docstring2md.__config__ import EX_CANTCREAT as EX_CANTCREAT, EX_IOERR as EX_IOERR, EX_OK as EX_OK, EX_OSFILE as EX_OSFILE, LOGGING_MSG as LOGGING_MSG, LOGGING_SETUP as LOGGING_SETUP
from docstring2md.log import logger as logger
from pathlib import Path
from typing import NamedTuple, Union

class MyFile(NamedTuple):
    path: Union[Path, None]
    exists: bool
    status: int
    @classmethod
    def set_path(cls, path: Union[str, None]) -> MyFile: ...
    def read(self) -> str: ...
    def write(self, data: str) -> int: ...
    def resolve(self) -> str: ...
    def absolute(self) -> str: ...
