class ConvMD:
    @staticmethod
    def repl_str(old_string, new_string): ...
    @staticmethod
    def repl_beg_end(begin_regexp: str, end_regexp: str, begin_tag: str, end_tag: str): ...
    @staticmethod
    def add_tag(begin_tag, end_tag): ...
