from pathlib import Path
from typing import NamedTuple, Union

class MyFile(NamedTuple):
    path: Union[Path, None]
    exists: bool
    status: int
    @classmethod
    def set_path(cls, path: Union[str, None]) -> MyFile: ...
    def read(self) -> str: ...
    def write(self, data: str) -> int: ...
    def resolve(self) -> str: ...
    def absolute(self) -> str: ...
