class PytMod:
    def __init__(self, module_name: str, priv: bool = ...) -> None: ...
    @property
    def module(self) -> str: ...
    @property
    def docstring(self) -> str: ...
    @property
    def pkg_main_docstring(self) -> str: ...
    @property
    def toc(self) -> str: ...
    def ismodule(self) -> bool: ...
    def read(self) -> None: ...
